package industries.geesawra.monarch.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// Blue Heeler theme: sky blue and warm gold, inspired by the Australian cattle dog

val BlueHeelerLightColorScheme = lightColorScheme(
    primary = Color(0xFF88CAFC),
    onPrimary = Color(0xFF2B2C41),
    primaryContainer = Color(0xFFD2EBFF),
    onPrimaryContainer = Color(0xFF404066),
    secondary = Color(0xFFEDCC6F),
    onSecondary = Color(0xFF2B2C41),
    secondaryContainer = Color(0xFFFFF4D6),
    onSecondaryContainer = Color(0xFF4A3B00),
    tertiary = Color(0xFF8FA8C4),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFD2EBFF),
    onTertiaryContainer = Color(0xFF404066),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFCFCFF),
    onBackground = Color(0xFF2B2C41),
    surface = Color(0xFFFCFCFF),
    onSurface = Color(0xFF2B2C41),
    surfaceVariant = Color(0xFFD2EBFF),
    onSurfaceVariant = Color(0xFF404066),
    outline = Color(0xFF8888A0),
    outlineVariant = Color(0xFFC8D8E8),
    inverseSurface = Color(0xFF2B2C41),
    inverseOnSurface = Color(0xFFD2EBFF),
    inversePrimary = Color(0xFF404066),
    surfaceTint = Color(0xFF88CAFC),
    scrim = Color(0xFF000000),
    surfaceContainer = Color(0xFFE8F2FF),
    surfaceContainerLow = Color(0xFFF0F7FF),
    surfaceContainerHigh = Color(0xFFDCE8F5),
    surfaceContainerHighest = Color(0xFFD2EBFF),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceDim = Color(0xFFC4D4E8),
    surfaceBright = Color(0xFFFCFCFF),
)

val BlueHeelerDarkColorScheme = darkColorScheme(
    primary = Color(0xFF88CAFC),
    onPrimary = Color(0xFF2B2C41),
    primaryContainer = Color(0xFF404066),
    onPrimaryContainer = Color(0xFFD2EBFF),
    secondary = Color(0xFFEDCC6F),
    onSecondary = Color(0xFF2B2C41),
    secondaryContainer = Color(0xFF5A4A20),
    onSecondaryContainer = Color(0xFFFFF4D6),
    tertiary = Color(0xFF8FA8C4),
    onTertiary = Color(0xFF2B2C41),
    tertiaryContainer = Color(0xFF3A4A5A),
    onTertiaryContainer = Color(0xFFD2EBFF),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF2B2C41),
    onBackground = Color(0xFFD2EBFF),
    surface = Color(0xFF2B2C41),
    onSurface = Color(0xFFD2EBFF),
    surfaceVariant = Color(0xFF404066),
    onSurfaceVariant = Color(0xFFA8B8D0),
    outline = Color(0xFF8888A0),
    outlineVariant = Color(0xFF404066),
    inverseSurface = Color(0xFFD2EBFF),
    inverseOnSurface = Color(0xFF2B2C41),
    inversePrimary = Color(0xFF88CAFC),
    surfaceTint = Color(0xFF88CAFC),
    scrim = Color(0xFF000000),
    surfaceContainer = Color(0xFF33334D),
    surfaceContainerLow = Color(0xFF2B2C41),
    surfaceContainerHigh = Color(0xFF3D3D5C),
    surfaceContainerHighest = Color(0xFF404066),
    surfaceContainerLowest = Color(0xFF1A1A2E),
    surfaceDim = Color(0xFF1A1A2E),
    surfaceBright = Color(0xFF4A4A6E),
)
