package industries.geesawra.monarch.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// Blue Heeler theme: sky blue and warm gold, inspired by Bluey

val BlueHeelerLightColorScheme = lightColorScheme(
    primary = Color(0xFF88CAFC),
    onPrimary = Color(0xFF001524),
    primaryContainer = Color(0xFFD2EBFF),
    onPrimaryContainer = Color(0xFF001524),
    secondary = Color(0xFFEDCC6F),
    onSecondary = Color(0xFF3D2F00),
    secondaryContainer = Color(0xFFEDCC6F),
    onSecondaryContainer = Color(0xFF1A1A1A),
    tertiary = Color(0xFF8FA8C4),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFD2EBFF),
    onTertiaryContainer = Color(0xFF001524),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFEAF4FF),
    onBackground = Color(0xFF001524),
    surface = Color(0xFFEAF4FF),
    onSurface = Color(0xFF001524),
    surfaceVariant = Color(0xFFD2EBFF),
    onSurfaceVariant = Color(0xFF9A7000),
    outline = Color(0xFF5A7A90),
    outlineVariant = Color(0xFFB8D8F0),
    inverseSurface = Color(0xFF001524),
    inverseOnSurface = Color(0xFFD2EBFF),
    inversePrimary = Color(0xFF88CAFC),
    surfaceTint = Color(0xFF88CAFC),
    scrim = Color(0xFF000000),
    surfaceContainer = Color(0xFFD6E8F5),
    surfaceContainerLow = Color(0xFFE0F0FF),
    surfaceContainerHigh = Color(0xFFC4DEEE),
    surfaceContainerHighest = Color(0xFFB0D0E8),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceDim = Color(0xFFA8C8E0),
    surfaceBright = Color(0xFFF5FAFF),
)

val BlueHeelerDarkColorScheme = darkColorScheme(
    primary = Color(0xFF88CAFC),
    onPrimary = Color(0xFF001524),
    primaryContainer = Color(0xFF2A4A66),
    onPrimaryContainer = Color(0xFFD2EBFF),
    secondary = Color(0xFFEDCC6F),
    onSecondary = Color(0xFF3D2F00),
    secondaryContainer = Color(0xFFEDCC6F),
    onSecondaryContainer = Color(0xFF1A1A1A),
    tertiary = Color(0xFF8FA8C4),
    onTertiary = Color(0xFF0F1620),
    tertiaryContainer = Color(0xFF1E2E40),
    onTertiaryContainer = Color(0xFFD2EBFF),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF0F1620),
    onBackground = Color(0xFFE8F4FF),
    surface = Color(0xFF0F1620),
    onSurface = Color(0xFFE8F4FF),
    surfaceVariant = Color(0xFF1E2E40),
    onSurfaceVariant = Color(0xFF9A7000),
    outline = Color(0xFF4A6A88),
    outlineVariant = Color(0xFF1E2E40),
    inverseSurface = Color(0xFFE8F4FF),
    inverseOnSurface = Color(0xFF0F1620),
    inversePrimary = Color(0xFF88CAFC),
    surfaceTint = Color(0xFF88CAFC),
    scrim = Color(0xFF000000),
    surfaceContainer = Color(0xFF1A2432),
    surfaceContainerLow = Color(0xFF141E2A),
    surfaceContainerHigh = Color(0xFF222E3E),
    surfaceContainerHighest = Color(0xFF2C3A4E),
    surfaceContainerLowest = Color(0xFF080C14),
    surfaceDim = Color(0xFF080C14),
    surfaceBright = Color(0xFF3A4A5E),
)
