package industries.geesawra.monarch.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// Catppuccin theme: Catppuccin-inspired purple primary

val CatppuccinLightColorScheme = lightColorScheme(
    primary = Color(0xFF8839EF),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFEBDDFF),
    onPrimaryContainer = Color(0xFF25005A),
    secondary = Color(0xFF645A71),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFEBDDF8),
    onSecondaryContainer = Color(0xFF1F172B),
    tertiary = Color(0xFF7F5261),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFD9E3),
    onTertiaryContainer = Color(0xFF31101E),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFEFF1F5),
    onBackground = Color(0xFF1E1E2E),
    surface = Color(0xFFEFF1F5),
    onSurface = Color(0xFF1E1E2E),
    surfaceVariant = Color(0xFFE6E9EF),
    onSurfaceVariant = Color(0xFF585B70),
    outline = Color(0xFF7C7F93),
    outlineVariant = Color(0xFFCCD0DA),
    inverseSurface = Color(0xFF313244),
    inverseOnSurface = Color(0xFFEFF1F5),
    inversePrimary = Color(0xFFD0BCFF),
    surfaceTint = Color(0xFF8839EF),
    scrim = Color(0xFF000000),
    surfaceContainer = Color(0xFFDBDDE1),
    surfaceContainerLow = Color(0xFFE5E7EB),
    surfaceContainerHigh = Color(0xFFD1D3D7),
    surfaceContainerHighest = Color(0xFFC7C9CD),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceDim = Color(0xFFCCD0DA),
    surfaceBright = Color(0xFFEFF1F5),
)

val CatppuccinDarkColorScheme = darkColorScheme(
    primary = Color(0xFFCBA6F7),
    onPrimary = Color(0xFF3C008D),
    primaryContainer = Color(0xFF5600C4),
    onPrimaryContainer = Color(0xFFEBDDFF),
    secondary = Color(0xFFCFC1DC),
    onSecondary = Color(0xFF352C41),
    secondaryContainer = Color(0xFF4C4258),
    onSecondaryContainer = Color(0xFFEBDDF8),
    tertiary = Color(0xFFF2B8C9),
    onTertiary = Color(0xFF4A2533),
    tertiaryContainer = Color(0xFF643B49),
    onTertiaryContainer = Color(0xFFFFD9E3),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF1E1E2E),
    onBackground = Color(0xFFCCD0DA),
    surface = Color(0xFF1E1E2E),
    onSurface = Color(0xFFCCD0DA),
    surfaceVariant = Color(0xFF45475A),
    onSurfaceVariant = Color(0xFFBCC0CC),
    outline = Color(0xFF8C8FA1),
    outlineVariant = Color(0xFF45475A),
    inverseSurface = Color(0xFFCCD0DA),
    inverseOnSurface = Color(0xFF313244),
    inversePrimary = Color(0xFF7E4BD0),
    surfaceTint = Color(0xFFCBA6F7),
    scrim = Color(0xFF000000),
    surfaceContainer = Color(0xFF343444),
    surfaceContainerLow = Color(0xFF2A2A3A),
    surfaceContainerHigh = Color(0xFF3E3E4E),
    surfaceContainerHighest = Color(0xFF484858),
    surfaceContainerLowest = Color(0xFF11111B),
    surfaceDim = Color(0xFF1E1E2E),
    surfaceBright = Color(0xFF45475A),
)
