package industries.geesawra.monarch.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// Deer theme: muted forest green primary (hsl 145)

val DeerLightColorScheme = lightColorScheme(
    primary = Color(0xFF3D7A4A),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFBEF2C8),
    onPrimaryContainer = Color(0xFF002109),
    secondary = Color(0xFF506352),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFD3E8D2),
    onSecondaryContainer = Color(0xFF0E1F12),
    tertiary = Color(0xFF3A656E),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFBEEBF5),
    onTertiaryContainer = Color(0xFF001F25),
    error = Color(0xFFE91646),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFF6FAF6),
    onBackground = Color(0xFF181D18),
    surface = Color(0xFFF6FAF6),
    onSurface = Color(0xFF181D18),
    surfaceVariant = Color(0xFFDDE5DA),
    onSurfaceVariant = Color(0xFF414941),
    outline = Color(0xFF717970),
    outlineVariant = Color(0xFFC1C9BE),
    inverseSurface = Color(0xFF2D322D),
    inverseOnSurface = Color(0xFFEEF2ED),
    inversePrimary = Color(0xFFA3D5AD),
    surfaceTint = Color(0xFF3D7A4A),
    scrim = Color(0xFF000000),
    surfaceContainer = Color(0xFFE3E7E3),
    surfaceContainerLow = Color(0xFFECF0EC),
    surfaceContainerHigh = Color(0xFFDADEDA),
    surfaceContainerHighest = Color(0xFFD1D5D1),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceDim = Color(0xFFD7DCD7),
    surfaceBright = Color(0xFFF6FAF6),
)

val DeerDarkColorScheme = darkColorScheme(
    primary = Color(0xFFA3D5AD),
    onPrimary = Color(0xFF0A391A),
    primaryContainer = Color(0xFF245233),
    onPrimaryContainer = Color(0xFFBEF2C8),
    secondary = Color(0xFFB7CCB7),
    onSecondary = Color(0xFF233426),
    secondaryContainer = Color(0xFF394B3B),
    onSecondaryContainer = Color(0xFFD3E8D2),
    tertiary = Color(0xFFA2CED8),
    onTertiary = Color(0xFF01363E),
    tertiaryContainer = Color(0xFF204D56),
    onTertiaryContainer = Color(0xFFBEEBF5),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF151D28),
    onBackground = Color(0xFFDFE5DE),
    surface = Color(0xFF151D28),
    onSurface = Color(0xFFDFE5DE),
    surfaceVariant = Color(0xFF414941),
    onSurfaceVariant = Color(0xFFC1C9BE),
    outline = Color(0xFF8B9389),
    outlineVariant = Color(0xFF414941),
    inverseSurface = Color(0xFFDFE5DE),
    inverseOnSurface = Color(0xFF2D322D),
    inversePrimary = Color(0xFF3D7A4A),
    surfaceTint = Color(0xFFA3D5AD),
    scrim = Color(0xFF000000),
    surfaceContainer = Color(0xFF28333E),
    surfaceContainerLow = Color(0xFF1F2732),
    surfaceContainerHigh = Color(0xFF313D49),
    surfaceContainerHighest = Color(0xFF3A4753),
    surfaceContainerLowest = Color(0xFF0B1015),
    surfaceDim = Color(0xFF151D28),
    surfaceBright = Color(0xFF353D48),
)
