package industries.geesawra.monarch.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// Kitty theme: purple/magenta primary (hsl 290) on cool blue-grey neutrals

val KittyLightColorScheme = lightColorScheme(
    primary = Color(0xFF8B4A91),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFD6FE),
    onPrimaryContainer = Color(0xFF36003D),
    secondary = Color(0xFF6B586B),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFF4DBF2),
    onSecondaryContainer = Color(0xFF251626),
    tertiary = Color(0xFF82524D),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFDAD6),
    onTertiaryContainer = Color(0xFF33110E),
    error = Color(0xFFE91646),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFFFBFF),
    onBackground = Color(0xFF1F1A1F),
    surface = Color(0xFFFFFBFF),
    onSurface = Color(0xFF1F1A1F),
    surfaceVariant = Color(0xFFECDFE9),
    onSurfaceVariant = Color(0xFF4D444C),
    outline = Color(0xFF7F747D),
    outlineVariant = Color(0xFFD0C3CD),
    inverseSurface = Color(0xFF352F34),
    inverseOnSurface = Color(0xFFF8EEF5),
    inversePrimary = Color(0xFFF5ABFB),
    surfaceTint = Color(0xFF8B4A91),
    scrim = Color(0xFF000000),
    surfaceContainer = Color(0xFFF4EAF2),
    surfaceContainerLow = Color(0xFFFAF0F8),
    surfaceContainerHigh = Color(0xFFEEE4EC),
    surfaceContainerHighest = Color(0xFFE8DEE6),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceDim = Color(0xFFE1D7DF),
    surfaceBright = Color(0xFFFFFBFF),
)

val KittyDarkColorScheme = darkColorScheme(
    primary = Color(0xFFF5ABFB),
    onPrimary = Color(0xFF541B5E),
    primaryContainer = Color(0xFF6E3277),
    onPrimaryContainer = Color(0xFFFFD6FE),
    secondary = Color(0xFFD7BFD5),
    onSecondary = Color(0xFF3B2B3B),
    secondaryContainer = Color(0xFF524153),
    onSecondaryContainer = Color(0xFFF4DBF2),
    tertiary = Color(0xFFF6B8B2),
    onTertiary = Color(0xFF4C2522),
    tertiaryContainer = Color(0xFF663B37),
    onTertiaryContainer = Color(0xFFFFDAD6),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF171217),
    onBackground = Color(0xFFE8DEE6),
    surface = Color(0xFF171217),
    onSurface = Color(0xFFE8DEE6),
    surfaceVariant = Color(0xFF4D444C),
    onSurfaceVariant = Color(0xFFD0C3CD),
    outline = Color(0xFF998D97),
    outlineVariant = Color(0xFF4D444C),
    inverseSurface = Color(0xFFE8DEE6),
    inverseOnSurface = Color(0xFF352F34),
    inversePrimary = Color(0xFF8B4A91),
    surfaceTint = Color(0xFFF5ABFB),
    scrim = Color(0xFF000000),
    surfaceContainer = Color(0xFF231E23),
    surfaceContainerLow = Color(0xFF1F1A1F),
    surfaceContainerHigh = Color(0xFF2E282D),
    surfaceContainerHighest = Color(0xFF393338),
    surfaceContainerLowest = Color(0xFF110D11),
    surfaceDim = Color(0xFF171217),
    surfaceBright = Color(0xFF3E373D),
)
