package industries.geesawra.monarch.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// Reddwarf theme: monochrome warm red/rust-brown

val ReddwarfLightColorScheme = lightColorScheme(
    primary = Color(0xFFC14C42),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFF0EE),
    onPrimaryContainer = Color(0xFF401D19),
    secondary = Color(0xFF93655F),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFF8E2DE),
    onSecondaryContainer = Color(0xFF401D19),
    tertiary = Color(0xFF714842),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFEACCC7),
    onTertiaryContainer = Color(0xFF2C0C09),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFFF7F5),
    onBackground = Color(0xFF2C0C09),
    surface = Color(0xFFFFF7F5),
    onSurface = Color(0xFF2C0C09),
    surfaceVariant = Color(0xFFF8E2DE),
    onSurfaceVariant = Color(0xFF5B342F),
    outline = Color(0xFF93655F),
    outlineVariant = Color(0xFFEACCC7),
    inverseSurface = Color(0xFF401D19),
    inverseOnSurface = Color(0xFFFFF0EE),
    inversePrimary = Color(0xFFEACCC7),
    surfaceTint = Color(0xFFC14C42),
    scrim = Color(0xFF000000),
    surfaceContainer = Color(0xFFEBE3E1),
    surfaceContainerLow = Color(0xFFF5EDEB),
    surfaceContainerHigh = Color(0xFFE1D9D7),
    surfaceContainerHighest = Color(0xFFD7CFCB),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceDim = Color(0xFFEACCC7),
    surfaceBright = Color(0xFFFFF7F5),
)

val ReddwarfDarkColorScheme = darkColorScheme(
    primary = Color(0xFFEACCC7),
    onPrimary = Color(0xFF5B342F),
    primaryContainer = Color(0xFF714842),
    onPrimaryContainer = Color(0xFFFFF0EE),
    secondary = Color(0xFFEACCC7),
    onSecondary = Color(0xFF5B342F),
    secondaryContainer = Color(0xFF714842),
    onSecondaryContainer = Color(0xFFF8E2DE),
    tertiary = Color(0xFFBD948E),
    onTertiary = Color(0xFF401D19),
    tertiaryContainer = Color(0xFF5B342F),
    onTertiaryContainer = Color(0xFFEACCC7),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF180000),
    onBackground = Color(0xFFEACCC7),
    surface = Color(0xFF180000),
    onSurface = Color(0xFFEACCC7),
    surfaceVariant = Color(0xFF5B342F),
    onSurfaceVariant = Color(0xFFEACCC7),
    outline = Color(0xFFBD948E),
    outlineVariant = Color(0xFF5B342F),
    inverseSurface = Color(0xFFEACCC7),
    inverseOnSurface = Color(0xFF401D19),
    inversePrimary = Color(0xFFC14C42),
    surfaceTint = Color(0xFFEACCC7),
    scrim = Color(0xFF000000),
    surfaceContainer = Color(0xFF321414),
    surfaceContainerLow = Color(0xFF280A0A),
    surfaceContainerHigh = Color(0xFF3C1E1A),
    surfaceContainerHighest = Color(0xFF462824),
    surfaceContainerLowest = Color(0xFF0E0000),
    surfaceDim = Color(0xFF180000),
    surfaceBright = Color(0xFF5B342F),
)
