package industries.geesawra.monarch.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// Witchsky theme: warm coral/red primary (hsl 5)
// Primary: hsl(5, 82%, 60%) = ~#E85A4F

val WitchskyLightColorScheme = lightColorScheme(
    primary = Color(0xFFE85A4F),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFDAD5),
    onPrimaryContainer = Color(0xFF3B0907),
    secondary = Color(0xFF775652),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFDAD5),
    onSecondaryContainer = Color(0xFF2C1512),
    tertiary = Color(0xFF715B2E),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFEDEA6),
    onTertiaryContainer = Color(0xFF261900),
    error = Color(0xFFE91646),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFEFBFB),
    onBackground = Color(0xFF1B1A1A),
    surface = Color(0xFFFEFBFB),
    onSurface = Color(0xFF1B1A1A),
    surfaceVariant = Color(0xFFF4DDDA),
    onSurfaceVariant = Color(0xFF534341),
    outline = Color(0xFF857370),
    outlineVariant = Color(0xFFD8C2BF),
    inverseSurface = Color(0xFF3D3A3A),
    inverseOnSurface = Color(0xFFF5EFEE),
    inversePrimary = Color(0xFFFFB4AB),
    surfaceTint = Color(0xFFE85A4F),
    scrim = Color(0xFF000000),
    surfaceContainer = Color(0xFFEDE6E5),
    surfaceContainerLow = Color(0xFFF5EEED),
    surfaceContainerHigh = Color(0xFFE5DEDD),
    surfaceContainerHighest = Color(0xFFDDD6D5),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceDim = Color(0xFFE0DADA),
    surfaceBright = Color(0xFFFEFBFB),
)

val WitchskyDarkColorScheme = darkColorScheme(
    primary = Color(0xFFFFB4AB),
    onPrimary = Color(0xFF5F1412),
    primaryContainer = Color(0xFF7D2B27),
    onPrimaryContainer = Color(0xFFFFDAD5),
    secondary = Color(0xFFE7BDB8),
    onSecondary = Color(0xFF442926),
    secondaryContainer = Color(0xFF5D3F3B),
    onSecondaryContainer = Color(0xFFFFDAD5),
    tertiary = Color(0xFFE0C38C),
    onTertiary = Color(0xFF3F2D04),
    tertiaryContainer = Color(0xFF584419),
    onTertiaryContainer = Color(0xFFFEDEA6),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF1B1A1A),
    onBackground = Color(0xFFE7E1E0),
    surface = Color(0xFF1B1A1A),
    onSurface = Color(0xFFE7E1E0),
    surfaceVariant = Color(0xFF534341),
    onSurfaceVariant = Color(0xFFD8C2BF),
    outline = Color(0xFFA08C8A),
    outlineVariant = Color(0xFF534341),
    inverseSurface = Color(0xFFE7E1E0),
    inverseOnSurface = Color(0xFF3D3A3A),
    inversePrimary = Color(0xFFBF4037),
    surfaceTint = Color(0xFFFFB4AB),
    scrim = Color(0xFF000000),
    surfaceContainer = Color(0xFF2E2B2B),
    surfaceContainerLow = Color(0xFF252222),
    surfaceContainerHigh = Color(0xFF373434),
    surfaceContainerHighest = Color(0xFF403D3D),
    surfaceContainerLowest = Color(0xFF0F0E0E),
    surfaceDim = Color(0xFF1B1A1A),
    surfaceBright = Color(0xFF423F3F),
)
