services:
  beepboop:
    labels:
      - wud.watch=true
      - wud.watch.digest=true
    image: ghcr.io/geesawra/monarch/beepboop:latest
    ports:
      - "9999:9999"
    env_file: ./stack.env
    volumes:
      - ./keys/firebase-key.json:/keys/firebase-key.json:ro
      - ./tokens:/app/tokens
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1024M

  prometheus:
    image: prom/prometheus:v3.11.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    restart: unless-stopped

  whatsupdocker:
    image: getwud/wud
    container_name: wud
    environment:
      - WUD_WATCHER_LOCAL_WATCHBYDEFAULT=false
      - WUD_TRIGGER_DOCKER_LOCAL_PRUNE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  prometheus-data:

