services:
  beepboop:
    image: ghcr.io/geesawra/monarch/beepboop:latest
    ports:
      - "9999:9999"
    env_file: ./stack.env
    volumes:
      - ./keys/firebase-key.json:/keys/firebase-key.json:ro
      - ./tokens:/app/tokens
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1024M

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    restart: unless-stopped

volumes:
  prometheus-data:
