FROM golang:1.26 AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /beepboop .

FROM gcr.io/distroless/static-debian12
COPY --from=build /beepboop /beepboop
ENTRYPOINT ["/beepboop"]
