engine: nixery

when:
  - event: [ "push", "pull_request" ]
    branch: [ "main" ]

dependencies:
  nixpkgs:
    - age
    - gnugrep
    - gnused
    - curl
    - unzip
    - findutils
    - zlib
    - glibc
    - gcc-unwrapped
    - fastlane
    - jdk21_headless
    - nodejs

steps:
  - name: build-release-apk
    command: |
      set -e
      JDK=/nix/store/$(ls /nix/store | grep openjdk-headless-21)
      source $JDK/nix-support/setup-hook
      source install-android-sdk.sh
      npm i -D wrangler@latest
      echo $AGE_KEY > age-key.txt
      age --decrypt -i age-key.txt -o app/keystore.jks keystore.jks.age
      
      fastlane release_bin
      source ./generate-root.sh app/build/outputs/apk/release/app-release.apk
      npx wrangler r2 object put monarch-releases/$MONARCH_APK_FILENAME --remote true --file=$MONARCH_APK_PATH
      npx wrangler r2 object put monarch-releases/index.html --remote true --file=./index.html
