engine: nixery

when:
  - event: ["push", "pull_request"]
    branch: ["main"]

dependencies:
  nixpkgs:
    - gnugrep
    - gnused
    - curl
    - unzip
    - findutils
    - fastlane
    - jdk24

environment:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
  LANGUAGE: "en_US.UTF-8"
  
steps:
  - name: build-release-apk
    command: |
      # grab the java home
      JDK=/nix/store/$(ls /nix/store | grep openjdk-24)

      chmod +x install-android-sdk.sh
      source $JDK/nix-support/setup-hook
      source install-android-sdk.sh
      
      ./gradlew assembleRelease
